In [1]:
pip install opencv-python

Defaulting to user installation because normal site-packages is not writeable
  Using cached numpy-2.4.2-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.2-cp312-cp312-win_amd64.whl (12.3 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.4.2 which is incompatible.
numba 0.59.1 requires numpy<1.27,>=1.22, but you have numpy 2.4.2 which is incompatible.
pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.4.2 which is incompatible.
scipy 1.13.1 requires numpy<2.3,>=1.22.4, but you have numpy 2.4.2 which is incompatible.
streamlit 1.32.0 requires numpy<2,>=1.19.3, but you have numpy 2.4.2 which is incompatible.


In [11]:
import cv2
print(cv2.__version__)
import numpy as np
import matplotlib.pyplot as plt

4.13.0


AttributeError: 'numpy.dtypes.BoolDType' object has no attribute 'bits'

In [5]:
img=cv2.imread(r'C:\Users\HP\Desktop\chayan\charizard.jpg')

In [6]:
print(img)

[[[  5   8  82]
  [  5   8  82]
  [  5   9  80]
  ...
  [  1   2   0]
  [  3   3   0]
  [  3   4   0]]

 [[  6   9  83]
  [  5   8  82]
  [  5   9  80]
  ...
  [  1   2   0]
  [  3   3   0]
  [  3   4   0]]

 [[  6   9  84]
  [  6   9  83]
  [  3   9  80]
  ...
  [  1   2   0]
  [  1   2   0]
  [  1   3   0]]

 ...

 [[ 44  63 250]
  [ 46  65 252]
  [ 47  66 253]
  ...
  [ 55  63 210]
  [ 59  68 212]
  [ 61  70 214]]

 [[ 44  63 250]
  [ 46  65 252]
  [ 47  66 253]
  ...
  [ 56  64 208]
  [ 60  69 210]
  [ 62  72 210]]

 [[ 44  63 250]
  [ 46  65 252]
  [ 47  66 253]
  ...
  [ 57  64 205]
  [ 60  70 207]
  [ 62  74 206]]]


In [7]:
print(img.shape)

(1309, 736, 3)


In [8]:
print(img.dtype)

uint8


In [9]:
print(img.size)

2890272


In [10]:
plt.imshow(img)

NameError: name 'plt' is not defined